export const LEVEL_THRESHOLDS = [
  { level: 1, xpRequired: 0, label: 'Beginner', color: '#6B7280' },
  { level: 2, xpRequired: 50, label: 'Elementary', color: '#1D9E75' },
  { level: 3, xpRequired: 150, label: 'Intermediate', color: '#D85A30' },
  { level: 4, xpRequired: 300, label: 'Advanced', color: '#410FA3' },
  { level: 5, xpRequired: 500, label: 'Master', color: '#F59E0B' },
];

export const LESSONS = [
  {
    id: 'kap-001',
    dialect: 'kapampangan',
    title: 'Basic Greetings',
    description: 'Learn how to greet people in Kapampangan',
    category: 'Greetings',
    requiredLevel: 1,
    xpReward: 20,
    words: 5,
  },
  {
    id: 'kap-002',
    dialect: 'kapampangan',
    title: 'Numbers 1-10',
    description: 'Learn numbers in Kapampangan',
    category: 'Numbers',
    requiredLevel: 2,
    xpReward: 30,
    words: 5,
  },
  {
    id: 'kap-003',
    dialect: 'kapampangan',
    title: 'Family Members',
    description: 'Learn family words in Kapampangan',
    category: 'Family',
    requiredLevel: 3,
    xpReward: 40,
    words: 5,
  },
  {
    id: 'tag-001',
    dialect: 'tagalog',
    title: 'Basic Greetings',
    description: 'Learn how to greet people in Tagalog',
    category: 'Greetings',
    requiredLevel: 1,
    xpReward: 20,
    words: 5,
  },
  {
    id: 'tag-002',
    dialect: 'tagalog',
    title: 'Numbers 1-10',
    description: 'Learn numbers in Tagalog',
    category: 'Numbers',
    requiredLevel: 2,
    xpReward: 30,
    words: 5,
  },
  {
    id: 'tag-003',
    dialect: 'tagalog',
    title: 'Family Members',
    description: 'Learn family words in Tagalog',
    category: 'Family',
    requiredLevel: 3,
    xpReward: 40,
    words: 5,
  },
  {
    id: 'war-001',
    dialect: 'waray',
    title: 'Basic Greetings',
    description: 'Learn how to greet people in Waray',
    category: 'Greetings',
    requiredLevel: 1,
    xpReward: 20,
    words: 5,
  },
  {
    id: 'war-002',
    dialect: 'waray',
    title: 'Numbers 1-10',
    description: 'Learn numbers in Waray',
    category: 'Numbers',
    requiredLevel: 2,
    xpReward: 30,
    words: 5,
  },
  {
    id: 'war-003',
    dialect: 'waray',
    title: 'Family Members',
    description: 'Learn family words in Waray',
    category: 'Family',
    requiredLevel: 3,
    xpReward: 40,
    words: 5,
  },
];